### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by zoeypark** [zoeypark/todo-app#1]
### 만들고자 하는 기능이 무엇인가요?
- todo 추가/삭제/수정 기능
- 메뉴 탭 

### 해당 기능 구현을 위해 할 일이 무엇인가요?
1. [ ] 삭제 버튼 기능 추가
2. [ ] 수정 버튼 추가 및 기능 추가
3. [ ] 메뉴 페이지 구현

### 예상 작업시간 3hr
